name: scanguard
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  hive_flutter: ^1.1.0
  flutter_screenutil: ^5.9.3
  connectivity: ^3.0.6
  logger: ^2.4.0
  lottie: ^3.1.2
  loading_animation_widget: ^1.2.1
  cached_network_image: ^3.4.0
  shimmer: ^3.0.0
  fluttertoast: ^8.2.8
  google_fonts: ^6.2.1
  dio: ^5.7.0
  flutter_onboarding_slider: ^1.0.11
  web3dart: ^2.3.1  # Dart library for interacting with Ethereum smart contracts
  http:
  permission_handler: ^11.3.1
  gif: ^2.3.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
